Repository githubschool/bells, pull requests merged in 2020-07, with the labels that each got.

#17 Update caption for Dodgetocat
  _slides/22-terrencegatsby.md
Labels: caption-update-project

#19 Update caption
  _slides/17-jeffjohnsonwedbush.md
Labels: new-caption-project

#11 Update caption to be more descriptive
  _slides/06-ericalloyd.md
Labels: caption-update-project

#10 Update caption to say hello
  _slides/02-SaturnForce-ec.md
Labels: hello-world

#12 Update Caption Description
  _slides/07-GeorgeStefanis.md
Labels: caption-update-project

#14 Update 08-abraham-lee-wedbush.md
  _slides/08-abraham-lee-wedbush.md
Labels: Version1

#28 Update caption with smaller description
  _slides/12-divyasamuel-wedbush.md
Labels: caption-update-project

#18 Updated caption to be more descriptive
  _slides/03-aaronjae.md
Labels: first-caption-project

#23 Give the kimonocat an awesome caption
  _slides/11-deras-wb.md
Labels: Kill Bill Vol. 3

#26 Change the caption of the image
  _slides/14-felipe-wedbush.md
Labels: caption-update-project

#25 Update 19-john-parks-wedbush.md
  _slides/19-john-parks-wedbush.md
Labels: caption-update-project

#9 Update Caption to make more awesome
  _slides/10-david-bennett-wedbush.md
Labels: good first issue

#24 Edit caption to more descriptive text
  _slides/09-cesar-gutierrez-wedbush.md
Labels: caption-update-project

#29 Update caption to be more descriptive
  _slides/15-hershkashyap.md
Labels: caption-update-project
